name: learn-github-actions
run-name: ${{ github.actor }} is cleaning up empty issues
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
steps:
  - uses: lee-dohm/close-matching-issues@v2
    with:
      query: 	'performance is:open is:issue'
      # token: ${{ secrets.GITHUB_TOKEN }}
